### ISSUE TITLE
Document stats file format

### ISSUE THREAD

**Issue by multimeric** [pratas/xs#2]
Currently the documentation says:
```
 -qf <statsFile>          load file: mean, standard deviation (when: -qt 2)
```

What this doesn't explain is the format of said file. From reading the source code, it looks like you're expecting a file with one or more lines, and each line has the format `mean:stdev`. This should be in the help output.

In addition, I'm not really sure when you would need a multi-line file. This should probably be explained also.

**Comment by multimeric** [comment]
As a consequence I'm getting the following error: `Error: unmatching size of stats`

**Comment by pratas** [comment]
Hi, please see file "README" (not README.am).
It is written there:

 -qf <statsFile>          load file: mean, standard deviation (when: -qt 2)
                          For a normal distribution there is the option of
                          load a file with mean and standard deviation:
                          "-qf FILE", vi FILE:
                          0.4:0.10
                          0.3:0.15
                          ...
                          0.1:0.01
                          If this option is not used an array with both will
                          be used (mean and stdev in init.h);

**Comment by pratas** [comment]
Perhaps is better to add it to the main helper...

**Comment by pratas** [comment]
done

**Comment by pratas** [comment]
Thank you for noticing!

**Comment by multimeric** [comment]
Thanks! That helps a lot, but it still doesn't explain when you need more than one line in the file? Is it one line per base position? Meaning that a length 100 read would need a 100-line stats file?

**Comment by multimeric** [comment]
Bump, I'm still confused about this.

**Comment by pratas** [comment]
Hi! Thank you for the patience, since I did not see your previous message (don't know why but it got lost).
Each line stands for the average and standard deviation of each base (by order of the sequences). The qualities will be simulated according to these characteristics. Therefore, the number of lines should be at least the size of the read with the largest number of bases. 

Example:

0.4:0.10
0.3:0.15
0.5.0.20

This will set the **first** base on each read to have a quality with an average of 0.4 and std. deviation of 0.1.
The **second** will base on each read will have a quality average of 0.3 and std. dev of 0.15.
The **third** will base on each read will have a quality average of 0.5 and std. dev of 0.20.

And so on...

I hope this helps.
Best regards,
D

**Comment by multimeric** [comment]
Great, thanks.
